### ISSUE TITLE
Placeholder for feature parity with EmrEtlRunner

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/dataflow-runner#11]
Particularly around robustness.

This is a bit of an unfair ticket - it involves:

* Doing a detailed review of the EmrEtlRunner EMR invocation and monitoring code
* Identifying any missing features in Dataflow Runner
* Adding tickets into 0.2.0
* Closing this ticket and de-scheduling it from the 0.2.0 milestone

**Comment by BenFradet** [comment]
So far:

- EBS: #4 
- Apps: #6 
- Ability to inspect step status and act on it (I don't really know it'll translate to df-runner yet)

**Comment by alexanderdean** [comment]
> Ability to inspect step status and act on it (I don't really know it'll translate to df-runner yet)

I think this is fiddly but doable, but will need further thought...

**Comment by BenFradet** [comment]
Having given some thought to the last point, I'm not sure it really applies to df-runner since it seems really snowplow specific. What do you think @alexanderdean ?

**Comment by alexanderdean** [comment]
Hmm - I hear you. Let's break out the last point into a separate ticket "Explore options around ..." and put it into 0.3.0. This way gives us some more time to consider different options and whether we have to have this in Dataflow Runner or if there is another way...
