### ISSUE TITLE
Short-circuit execution on unset template variable

### ISSUE THREAD

**Issue by chuwy** [snowplow/dataflow-runner#16]
If user didn't set some template variable via `--vars`, step is still running with `"<no value>"` as a value, which in most cases not what user wants, but default [text/template behavior](https://golang.org/pkg/text/template/#Template.Option).

I think we should instead short-circuit execution of dataflow-runner. If user wants to leave it blank he may use whole `text/template` template language.

**Comment by alexanderdean** [comment]
Agree!

**Comment by chuwy** [comment]
Problem with template language though is that it adds double quotes.

**Comment by BenFradet** [comment]
Does it make sense to short-circuit for unset env variables with the `systemEnv` template function?

**Comment by BenFradet** [comment]
^ what do you think @chuwy ?

**Comment by chuwy** [comment]
Yep. That's how I'd expect it to work.
