### ISSUE TITLE
Fix hardcoded application version

### ISSUE THREAD

**Issue by chuwy** [snowplow/dataflow-runner#23]
https://github.com/snowplow/dataflow-runner/blob/master/src/main.go#L34

**Comment by alexanderdean** [comment]
Is the plan to fetch this at build time from the `VERSION` file?

**Comment by BenFradet** [comment]
I was thinking of updating it as part of the "Prepared for release" commit like the other artifacts.

**Comment by alexanderdean** [comment]
That's fine, per https://github.com/snowplow/sql-runner/commit/5dc8dffc3cb8919e8840733f250ad72fb4aba8c5

**Comment by BenFradet** [comment]
Descheduling and closing since this is part of the "Prepared for release commit": 49b9fd0c9c16e8e81ac503d29b3cb9ed560855c3
