### ISSUE TITLE
Add tags to playbook format

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/dataflow-runner#27]
A top level property, typed as a `map[string]string`:

```json
      ...
      "secretAccessKey": "env"
    },
    "tags": {
      "client": "Acme Inc",
      "environment": "staging"
    },
},

**Comment by alexanderdean** [comment]
Shout if you have any questions about this one @BenFradet !

**Comment by BenFradet** [comment]
should be straightforward enough

**Comment by BenFradet** [comment]
Just so we're on the same page, there is nothing on the side of EMR that would reflect this (i.e. you can't add tags to your jobflow steps).

**Comment by BenFradet** [comment]
Also tags in the cluster config are in the format which EMR expects:

```json
    "tags": [
      {
        "key": "client",
        "value": "com.engineering"
      },
      {
        "key": "job",
        "value": "main"
      }
    ]
```

should we keep the same format?

**Comment by alexanderdean** [comment]
Yep let's keep the same format, and agree - the tags in the playbook don't make it into the cluster...
