### ISSUE TITLE
Replace hard-coded template name by the file name

### ISSUE THREAD

**Issue by BenFradet** [snowplow/dataflow-runner#28]
https://github.com/snowplow/dataflow-runner/blob/master/src/config_resolver.go#L210

```golang
t, err := template.New("playbook").Funcs(templFuncs).Parse(string(rawBytes))
```

generates an error that might be misleading.

e.g. if someone forgets to specify a template variable in `cluster.json`, the generated error will be:

```
template: playbook:1:10: executing "playbook" at <.var>: map has no entry for key "var"
```

**Comment by BenFradet** [comment]
I reckon the best template name would be the filename, what do you think @alexanderdean ?

**Comment by alexanderdean** [comment]
Yep agree! (Wow the original impl is confusing)

**Comment by BenFradet** [comment]
I just noticed it while writing the blog post :smile:
