### ISSUE TITLE
Add option to fetch logs of failing jobflow step 

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/dataflow-runner#40]
If a jobflow step fails, it would be nice to retrieve the logs for that step and write them out to Dataflow Runner's own stdout/err.

This prevents the operator having to connect to EMR and fetch them themself.

**Comment by chuwy** [comment]
This can have quite different behaviors for spark submit, plain custom jar and other ways to run EMR jobs. But if we assume that this feature is just for `CUSTOM_JAR` - we'll be able to use it with RDB Loader to retrieve stdout logs and drop approach with logkey.

**Comment by alexanderdean** [comment]
This is the key feature which is driving the 0.4.0 release (other features can potentially be pushed back @BenFradet )

**Comment by BenFradet** [comment]
@alexanderdean shouldn't this be the default?

**Comment by alexanderdean** [comment]
I think best to leave it as an option, in case the operator doesn't want the orchestration box retrieving the log files and printing them out...
