### ISSUE TITLE
Add support for specifying applications to install on cluster 

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/dataflow-runner#6]

**Comment by jbeemster** [comment]
Are these applications that are usually installed using Jobflow Steps?

**Comment by BenFradet** [comment]
FYI, we're using Elasticity's applications in EmrEtlRunner:
- [here](https://github.com/snowplow/snowplow/pull/3048/files#diff-d7de3e27e5cf9941de4e37b1373b3bf3R145)
- [and here](https://github.com/snowplow/snowplow/pull/3048/files#diff-d7de3e27e5cf9941de4e37b1373b3bf3R359)

which seem to be added to the payload here:

https://github.com/rslifka/elasticity/blob/master/lib/elasticity/job_flow.rb#L221

**Comment by alexanderdean** [comment]
Assigning to Ben 😄
